-- Create table for flagged stations (stations that users report as non-existent)
CREATE TABLE IF NOT EXISTS flagged_stations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  station_id BIGINT REFERENCES stations(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  reason TEXT DEFAULT 'Station does not exist',
  
  -- Ensure a user can only flag a station once
  UNIQUE(station_id, user_id)
);

-- Enable RLS
ALTER TABLE flagged_stations ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view all flagged stations
CREATE POLICY "Anyone can view flagged stations" ON flagged_stations
  FOR SELECT TO authenticated
  USING (true);

-- Policy: Users can insert their own flags
CREATE POLICY "Users can flag stations" ON flagged_stations
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can delete their own flags
CREATE POLICY "Users can unflag stations" ON flagged_stations
  FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_flagged_stations_station_id ON flagged_stations(station_id);
CREATE INDEX IF NOT EXISTS idx_flagged_stations_user_id ON flagged_stations(user_id);
