-- Add push_notifications_enabled column to profiles if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'push_notifications_enabled') THEN
        ALTER TABLE profiles ADD COLUMN push_notifications_enabled BOOLEAN DEFAULT TRUE;
    END IF;
END $$;

-- Ensure notifications table exists
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  station_id BIGINT REFERENCES stations(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE
);

-- Enable RLS on notifications
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- Policy: Users can see their own notifications
DROP POLICY IF EXISTS "Users can view own notifications" ON notifications;
CREATE POLICY "Users can view own notifications" ON notifications
  FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

-- Function to handle new price reports / reviews
CREATE OR REPLACE FUNCTION handle_new_price_report()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  station_name TEXT;
  notif_message TEXT;
BEGIN
  -- Get station name
  SELECT name INTO station_name FROM stations WHERE id = NEW.station_id;
  
  -- Construct message based on what was updated
  IF NEW.price IS NOT NULL THEN
    notif_message := 'Price update at ' || station_name || ': ' || NEW.fuel_type || ' is now ' || NEW.price;
  ELSIF NEW.notes IS NOT NULL AND NEW.notes <> '' THEN
    notif_message := 'New review for ' || station_name || ': "' || left(NEW.notes, 50) || (CASE WHEN length(NEW.notes) > 50 THEN '...' ELSE '' END) || '"';
  ELSE
    -- If it's just a rating or something else we don't care about for now
    RETURN NEW;
  END IF;

  -- Insert notifications for all users who favorited this station AND have notifications enabled
  -- This INCLUDES the user who made the report (as requested)
  -- Also checks the global push_notifications_enabled setting in profiles
  INSERT INTO notifications (user_id, station_id, message)
  SELECT fs.user_id, NEW.station_id, notif_message
  FROM favourite_stations fs
  JOIN profiles p ON fs.user_id = p.id
  WHERE fs.station_id = NEW.station_id
    AND fs.notifications_enabled = true
    AND (p.push_notifications_enabled IS TRUE OR p.push_notifications_enabled IS NULL);

  RETURN NEW;
END;
$$;

-- Create the trigger
DROP TRIGGER IF EXISTS on_price_report_insert ON price_reports;
CREATE TRIGGER on_price_report_insert
AFTER INSERT ON price_reports
FOR EACH ROW
EXECUTE FUNCTION handle_new_price_report();
