-- Create the suggested_fuel_stations table
CREATE TABLE suggested_fuel_stations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  address TEXT,
  submitted_by UUID REFERENCES auth.users(id),
  status TEXT DEFAULT 'pending'
);

-- Enable Row Level Security (RLS)
ALTER TABLE suggested_fuel_stations ENABLE ROW LEVEL SECURITY;

-- Policy to allow authenticated users to insert suggestions
CREATE POLICY "Allow authenticated insert" ON suggested_fuel_stations
  FOR INSERT TO authenticated
  WITH CHECK (true);

-- Policy to allow users to view their own suggestions (optional)
CREATE POLICY "Allow users to view own suggestions" ON suggested_fuel_stations
  FOR SELECT TO authenticated
  USING (auth.uid() = submitted_by);

-- Create the approve_station function
create or replace function approve_station(suggested_id bigint)
returns json
language plpgsql
security definer
as $$
declare
  suggestion record;
  new_station_id bigint;
begin
  -- Get the suggestion
  select * into suggestion from suggested_fuel_stations where id = suggested_id;
  
  if suggestion is null then
    raise exception 'Suggestion not found';
  end if;

  -- Insert into main stations table
  insert into stations (name, latitude, longitude, address, submitted_by, status)
  values (suggestion.name, suggestion.latitude, suggestion.longitude, suggestion.address, suggestion.submitted_by, 'active')
  returning id into new_station_id;

  -- Update suggestion status
  update suggested_fuel_stations set status = 'approved' where id = suggested_id;

  return json_build_object('success', true, 'station_id', new_station_id);
end;
$$;
