-- Track user activity signals and expose richer moderation metrics.

-- 1) Raw activity events from client heartbeats/session starts.
CREATE TABLE IF NOT EXISTS public.user_activity_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    event_source TEXT NOT NULL DEFAULT 'mobile_app',
    platform TEXT,
    app_version TEXT,
    session_id TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_user_activity_events_user_created
    ON public.user_activity_events (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_user_activity_events_created
    ON public.user_activity_events (created_at DESC);

ALTER TABLE public.user_activity_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can insert own activity events" ON public.user_activity_events;
CREATE POLICY "Users can insert own activity events"
    ON public.user_activity_events
    FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own activity events" ON public.user_activity_events;
CREATE POLICY "Users can view own activity events"
    ON public.user_activity_events
    FOR SELECT
    TO authenticated
    USING (auth.uid() = user_id);

-- 2) Summary row per user for fast moderation queries.
CREATE TABLE IF NOT EXISTS public.user_activity_summary (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    last_active_at TIMESTAMPTZ,
    last_event_type TEXT,
    last_event_source TEXT,
    last_platform TEXT,
    last_app_version TEXT,
    last_session_id TEXT,
    total_events BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_user_activity_summary_last_active
    ON public.user_activity_summary (last_active_at DESC);

ALTER TABLE public.user_activity_summary ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own activity summary" ON public.user_activity_summary;
CREATE POLICY "Users can view own activity summary"
    ON public.user_activity_summary
    FOR SELECT
    TO authenticated
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own activity summary" ON public.user_activity_summary;
CREATE POLICY "Users can insert own activity summary"
    ON public.user_activity_summary
    FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own activity summary" ON public.user_activity_summary;
CREATE POLICY "Users can update own activity summary"
    ON public.user_activity_summary
    FOR UPDATE
    TO authenticated
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- 3) RPC used by mobile app to emit heartbeat/session activity.
CREATE OR REPLACE FUNCTION public.record_user_activity(
    p_event_type TEXT DEFAULT 'app_foreground',
    p_event_source TEXT DEFAULT 'mobile_app',
    p_platform TEXT DEFAULT NULL,
    p_app_version TEXT DEFAULT NULL,
    p_session_id TEXT DEFAULT NULL,
    p_metadata JSONB DEFAULT '{}'::jsonb
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
    v_user_id UUID := auth.uid();
    v_now TIMESTAMPTZ := now();
    v_event_type TEXT := COALESCE(NULLIF(trim(p_event_type), ''), 'app_foreground');
    v_event_source TEXT := COALESCE(NULLIF(trim(p_event_source), ''), 'mobile_app');
BEGIN
    IF v_user_id IS NULL THEN
        RETURN jsonb_build_object('success', false, 'message', 'Not authenticated');
    END IF;

    INSERT INTO public.user_activity_events (
        user_id,
        event_type,
        event_source,
        platform,
        app_version,
        session_id,
        metadata,
        created_at
    )
    VALUES (
        v_user_id,
        v_event_type,
        v_event_source,
        p_platform,
        p_app_version,
        p_session_id,
        COALESCE(p_metadata, '{}'::jsonb),
        v_now
    );

    INSERT INTO public.user_activity_summary (
        user_id,
        last_active_at,
        last_event_type,
        last_event_source,
        last_platform,
        last_app_version,
        last_session_id,
        total_events,
        updated_at
    )
    VALUES (
        v_user_id,
        v_now,
        v_event_type,
        v_event_source,
        p_platform,
        p_app_version,
        p_session_id,
        1,
        v_now
    )
    ON CONFLICT (user_id) DO UPDATE
    SET
        last_active_at = EXCLUDED.last_active_at,
        last_event_type = EXCLUDED.last_event_type,
        last_event_source = EXCLUDED.last_event_source,
        last_platform = EXCLUDED.last_platform,
        last_app_version = EXCLUDED.last_app_version,
        last_session_id = EXCLUDED.last_session_id,
        total_events = public.user_activity_summary.total_events + 1,
        updated_at = EXCLUDED.updated_at;

    -- Keep legacy device signal in sync when device rows exist.
    UPDATE public.user_devices
    SET last_seen_at = v_now
    WHERE user_id = v_user_id;

    RETURN jsonb_build_object('success', true, 'message', 'Activity recorded');
END;
$function$;

GRANT EXECUTE ON FUNCTION public.record_user_activity(TEXT, TEXT, TEXT, TEXT, TEXT, JSONB) TO authenticated;

-- 4) Backfill activity summary for existing users from known signals.
WITH device_last_seen AS (
    SELECT ud.user_id, max(ud.last_seen_at) AS last_seen_at
    FROM public.user_devices ud
    GROUP BY ud.user_id
),
content_activity AS (
    SELECT x.user_id, max(x.created_at) AS last_content_at
    FROM (
        SELECT pr.user_id, pr.created_at
        FROM public.price_reports pr
        UNION ALL
        SELECT rv.user_id, rv.created_at
        FROM public.reviews rv
        UNION ALL
        SELECT sfs.submitted_by AS user_id, sfs.created_at
        FROM public.suggested_fuel_stations sfs
        UNION ALL
        SELECT fs.user_id, fs.created_at
        FROM public.flagged_stations fs
        UNION ALL
        SELECT fav.user_id, fav.created_at
        FROM public.favourite_stations fav
    ) x
    GROUP BY x.user_id
)
INSERT INTO public.user_activity_summary (
    user_id,
    last_active_at,
    last_event_type,
    last_event_source,
    total_events,
    updated_at
)
SELECT
    p.id,
    NULLIF(
        GREATEST(
            COALESCE(au.last_sign_in_at, '-infinity'::timestamptz),
            COALESCE(dls.last_seen_at, '-infinity'::timestamptz),
            COALESCE(ca.last_content_at, '-infinity'::timestamptz),
            COALESCE(p.created_at, '-infinity'::timestamptz)
        ),
        '-infinity'::timestamptz
    ) AS last_active_at,
    'backfill',
    'system',
    0,
    now()
FROM public.profiles p
LEFT JOIN auth.users au ON au.id = p.id
LEFT JOIN device_last_seen dls ON dls.user_id = p.id
LEFT JOIN content_activity ca ON ca.user_id = p.id
ON CONFLICT (user_id) DO UPDATE
SET
    last_active_at = COALESCE(EXCLUDED.last_active_at, public.user_activity_summary.last_active_at),
    updated_at = now();

